export const SET_COUNTRIES = "SET_COUNTRIES"
export const SET_SEARCH_TERM = "SET_SEARCH_TERM"
export const SET_FILTER_TERM = "SET_FILTER_TERM"

export const SET_COUNTRY_CODE = "SET_COUNTRY_CODE"
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL"

export const SEARCH_COUNTRY = "SEARCH_COUNTRY"
export const SEARCH_COUNTRY_SUCCESS = "SEARCH_COUNTRY_SUCCESS"
export const SEARCH_COUNTRY_FAIL = "SEARCH_COUNTRY_FAIL"

export const FILTER_REGION = "FILTER_REGION"